### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by ses4j** [BirdVox/birdvoxpaint#3]
I ran the exact code in the README with a WAV file I had locally.  it ran, printed this:

> 1it [00:00, 124.99it/s]

Then it quit.  

I am on Windows, with Python 3.7.9.  I'm not even sure what it should have done, though.  ;)

**Comment by lostanlen** [comment]
Hello @ses4j. How long is the audio file in your `wav_path`? With the default parameters, i would recommend at least one minute, and up to two hours
If smaller than one minute, consider reducing the segment duration: e.g., `segment_duration=1`

**Comment by ses4j** [comment]
@lostanlen Thanks for responding!  I made a 2 minute file, and still nothing.  This is what I ran:

```import birdvoxpaint as bvp

wav_path = "test-2minute.wav"

X = bvp.transform(
    wav_path,
    # segment_duration=1,
    indices=[
        bvp.acoustic_complexity_index,
        bvp.entropy_based_concentration,
        bvp.acoustic_event_count,
    ],
)
bvp.rgbshow(X)
```

and this is what i got.
```
(.venv) C:\wc\record-nfc>py bvp.py
15it [00:00, 681.84it/s]
```

Should it be popping up a GUI window? Outputting a file?

**Comment by lostanlen** [comment]
ok good. if you run the above in an active Python session, then X will be a tensor with three time--frequency slice: acoustic complexity index, entropy-based concentration, and acoustic event count. You may use these features however you wish.

For a two-minute file you should find ~12 time samples in the input (by default the segment duration equals 10 seconds)

furthermore, if you run the above in a Jupyter notebook, it will display the tensor X as an RGB image.
R = acoustic complexity index, G = entropy-based concentration, B = acoustic event count

**Comment by beasteers** [comment]
@ses4j just a quick note - you need to do `plt.show()` after to see the matplotlib window.

Here's a slightly more complete example
```python
import birdvoxpaint as bvp
import matplotlib.pyplot as plt

# get some audio file
import librosa
audio_path = librosa.example('nutcracker')

# calculate acoustic indices
X = bvp.transform(
    audio_path, segment_duration=3, indices=[
        bvp.acoustic_complexity_index,
        bvp.entropy_based_concentration,
        bvp.acoustic_event_count,
    ])

print(X.shape)

# show
bvp.rgbshow(X)
plt.show()
```
